version: '3.8'
services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:latest
    ports:
      - "26379:6379"
    environment:
      REDIS_PASSWORD: "1234"

  server1:
    depends_on:
      - redis
    hostname: server1
    container_name: server1
    image: ojt90902/consistenthash-test:latest
    ports:
      - "28080:8080"
    environment:
      nodename: "server1"

  server2:
    depends_on:
      - redis
    hostname: server2
    container_name: server2
    image: ojt90902/consistenthash-test:latest
    ports:
      - "28081:8080"
    environment:
      nodename: "server2"


  server3:
    depends_on:
      - redis
    hostname: server3
    container_name: server3
    image: ojt90902/consistenthash-test:latest
    ports:
      - "28082:8080"
    environment:
      nodename: "server3"

  server4:
    depends_on:
      - redis
    hostname: server4
    container_name: server4
    image: ojt90902/consistenthash-test:latest
    ports:
      - "28083:8080"
    environment:
      nodename: "server4"

  server5:
    depends_on:
      - redis
    hostname: server5
    container_name: server5
    image: ojt90902/consistenthash-test:latest
    ports:
      - "28084:8080"
    environment:
      nodename: "server5"